server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        default_schema: moview
        jdbc:
          time_zone: UTC
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    schemas: moview
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: admin

# actuator
management:
  endpoint:
    health:
      show-details: always