server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:admin}

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        default_schema: moview
        jdbc:
          time_zone: UTC
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    schemas: moview
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

# actuator
management:
  endpoint:
    health:
      show-details: always